# Generated by Django 5.0.4 on 2024-04-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_loan_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='id_lender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
